### ISSUE TITLE
Can we create our own adventure?

### ISSUE THREAD

**Issue by Nerdietony** [brandon-rhodes/python-adventure#19]
Can we?

**Comment by bignose-debian** [comment]
On 01-Dec-2016, Antonio Vallez wrote:
> Can we?

Who could stop you?

-- 
 \          “The only tyrant I accept in this world is the still voice |
  `\                                      within.” —Mohandas K. Gandhi |
_o__)                                                                  |
Ben Finney <ben@benfinney.id.au>

**Comment by Nerdietony** [comment]
No one, I was hoping there were some tutorial explain how to set up an adventure

**Comment by Nerdietony** [comment]
No one, I was hoping there were some tutorial explain how to set up an adventure

**Comment by bignose-debian** [comment]
On 01-Dec-2016, Antonio Vallez wrote:
> I was hoping there were some tutorial explain how to set up an adventure

This library, ‘python-adventure’, is an implementation of the classic
1970s interactive fiction game Colossal Cave Adventure. It is highly
specialised to that purpose and IMO is not suitable for implementing
other interactive fiction.

Python libraries for writing interactive fiction, licensed under terms
repsecting software freedom, include the Python Universe Builder
<URL:http://py-universe.sourceforge.net/>.

-- 
 \       “As far as the laws of mathematics refer to reality, they are |
  `\    not certain, and as far as they are certain, they do not refer |
_o__)                              to reality.” —Albert Einstein, 1983 |
Ben Finney <ben@benfinney.id.au>

**Comment by brandon-rhodes** [comment]
Good evening, @Nerdietony!

This old port of the original Adventure program is not, alas, at all suitable to general-purpose use. Almost every specific bit of game design is hard-wired into its code: the way that Dwarves move, the chances of a thrown axe making a hit, and even the special logic regarding the Bear in the Barren Room are all hard-coded. To make it follow a different set of rules for a new adventure game, it would need to be rewritten.

So I would also recommend looking into a more modern interactive fiction framework, one that does not have hard-wired assumptions about what happens when you unchain the bear, or about how far you can go in the dark without breaking your neck. Good luck, and I hope you find great joy in creating your own little worlds!

**Comment by brandon-rhodes** [comment]
As you begin to learn adventure game programming, let us know if you do read the source code to Adventure and have specific questions — until then, I am going to close this issue for now to try to keep my dashboard a bit less busy. Simply comment again if you have any further questions, @Nerdietony!
