### ISSUE TITLE
Avoid traceback/name errors

### ISSUE THREAD

**Issue by gamesbook** [brandon-rhodes/python-adventure#20]
It would give a better "flavour" if the program did not respond:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ws' is not defined
```
or
```
  File "<stdin>", line 1
    open grate
             ^
SyntaxError: invalid syntax
```
when a faulty input is given.  Perhaps:
```
SORRY, I DO NOT UNDERSTAND "ws"
```
would be a better response.

**Comment by bignose-debian** [comment]
On 17-Feb-2017, Derek Hohls wrote:
> It would give a better "flavour" if the program did not respond […]
> ```
> NameError: name 'ws' is not defined
> ```
> when a faulty input is given.

This occurs when the `adventure.play` function is used.

The purpose of that is to allow the Python prompt to continue to
function as a Python prompt; that is, any command not recodnised
should instead be understood as a Python statement.

This necessarily entails that many actions will give the results as a
Python interpreter (not the Adventure interpreter).

> Perhaps:
> ```
> SORRY, I DO NOT UNDERSTAND "ws"
> ```
> would be a better response.

When you run the program as the main module:

    $ python3 -m adventure

it no longer attempts to read any command as a Python statement:

    > ws
    I DON'T KNOW THAT WORD.

So, you can get that behaviour by running Adventure as a program,
instead of at the Python prompt. Is that good enough?

-- 
 \         “Pinky, are you pondering what I'm pondering?” “I think so, |
  `\     Brain, but if they called them ‘Sad Meals’, kids wouldn't buy |
_o__)                                    them!” —_Pinky and The Brain_ |
Ben Finney <ben@benfinney.id.au>

**Comment by gamesbook** [comment]
That makes sense - thanks.
