### ISSUE TITLE
Packing

### ISSUE THREAD

**Issue by alan-zxs** [brandon-rhodes/python-adventure#29]
I am very glad that you managed to port this old game to Python.
It works well through the Python terminal.
But I would like to build an .exe file for other people who don't have Python installed, and I don't understand how to do this.

If I build it using the command:
`pyinstaller --onefile adventure/__main__.py`
The .exe file will throw an error that the readline module is not found.

If I create a new script `play.py`:
```python
import adventure
adventure.play()
```
and then package it, it won't be able to find the `advent.dat` file.

Do you have any ideas on how to package the game into an .exe file?

**Comment by brandon-rhodes** [comment]
Alas, no; I don't myself have a Windows machine, and it has been ten years since I [last tried out some tools for building EXE files](https://www.youtube.com/watch?v=wsczq6j3_bA). So, for now, this `adventure` module is only going to support `pip` installation. I'm going to go ahead and close this issue since third-party installer support isn't currently a goal.

But, you will still have permission to publish further comments here, so feel free to offer further comments on the closed issue if you make progress that you want to report, or if you find a way to get the `.exe` working and want to suggest tweaks to this module that might make `.exe` generation easier.

Thanks for your interest in the project!
