### ISSUE TITLE
Explicit grant of license

### ISSUE THREAD

**Issue by bignose-debian** [brandon-rhodes/python-adventure#4]
The code base is subject to copyright, but there is no copyright notice and no explicit grant of license. Recipients of the work can reasonably assume they have no valid license to copy, modify, and/or redistribute the work.

Please make an explicit grant of license in the work itself, citing specific license terms, and clarifying the grant is from the specific copyright holders.

**Comment by bignose-debian** [comment]
The work currently makes mention of a whole category of license terms, “BSD”, with no explicit grant of license.

Here is [a suggested change set](https://notabug.org/bignose/python-adventure/src/license-bsd-2) that sets copyright notices and explicitly grants license under the terms of the BSD 2-clause license.

**Comment by bignose-debian** [comment]
A stronger recommendation is to choose the terms of the Apache License version 2.0, which grants the same freedoms as above but also grants good protection against patent restrictions.

Here is a [suggested change set](https://notabug.org/bignose/python-adventure/src/license-apache-2) that sets copyright notices and explicitly grants license under the terms of the Apache License version 2.0.

**Comment by brandon-rhodes** [comment]
I cannot clarify the license terms on my own because I have not seen a clear statement of the terms under which the original Adventure game is licensed, of which this is a derived work. It is available for download from many sources, with the knowledge of the original authors, from whom I have never seen any complaint about its availability — but I have never seen a clear statement from them of the license under which they bless distribution.

I am going to close this issue until such time as a license from the original authors can be discovered. If you ever find the terms under which they are making the old code available, then please let me know by re-opening this issue and providing a link, and I'll respond as soon by clarifying the license of this derived work.

Thanks for your interest, and I hope we someday run across information that can get this question sorted out!

**Comment by bignose-debian** [comment]
I've researched this and put my conclusions at [a question on StackExchange](https://opensource.stackexchange.com/questions/1893/what-is-the-copyright-status-of-colossal-cave-adventure/)

Summary: due to the date and conditions of its publication, and the strange window of different copyright laws at the time, I conclude the 350-point Colossal Cave Adventure published in the 1970s is now public domain in the USA.

**Comment by bignose-debian** [comment]
Here's a direct link to [the answer with my conclusions](http://opensource.stackexchange.com/a/1917/2307).

So I think your derived work from the 1970s Colossal Cave Adventure work is under whatever license you choose. (I'd suggest the [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0.txt), if you're asking.) My [suggested change set](https://notabug.org/bignose/python-adventure/src/license-apache-2) grants that license effectively.

**Comment by brandon-rhodes** [comment]
First: thank you for braving a Stack Exchange site that is still working out which questions are on-topic! That first answer pointed out really excellent resources for answering the question.

And the answer involves the 1978 change in copyright law! I ought to have known that — as a boy, I remember reading about how you no longer needed to send works to Washington but could magically give them a legal status simply by affixing a magic © symbol. I just looked it up the article, thanks to archive.org, and it was in the November 1986 issue of the Rainbow Magazine for the Radio Shack Color Computer, in Jim Reed’s column:

https://archive.org/stream/rainbowmagazine-1986-11/The_Rainbow_Magazine_11_1986#page/n15/mode/2up

Your recommendation of license is a good one, but when donating my work on a project to an open source community I tend to stick with their default — and since I think of this as a fun hack that I threw together for other Python programmers to play with (they laughed when they saw I'd overridden `__repr__()` to make it playable from the command line), I am going to go with the same MIT license that Python itself ships with.

Thank you VERY much for your footwork on this. I am going to put together the diff now!

**Comment by brandon-rhodes** [comment]
I merged two of your commits, and then did the file annotations myself to make them a bit briefer. (I did not recognize the message you were pasting in — it's not the official one from the appendix to the Apache license itself, so I was not sure of its provenance?)

Thanks for helping me figure out the situation and get this documented!
