### ISSUE TITLE
Install stand-alone program via Setuptools “entry points”

### ISSUE THREAD

**Issue by bignose-debian** [brandon-rhodes/python-adventure#8]
The Setuptools “entry points” feature parses a specified Python callable, and will at install time set up external entry points. For “console scripts” this installs a stand-alone program for the specified entry point.

Please add a “console_scripts” entry point to install a stand-alone ‘adventure’ program.

**Comment by bignose-debian** [comment]
This requires resolution of issue #7 to allow import of the `__main__` module.

At https://notabug.org/bignose/python-adventure/commits/feature/wip/stand-alone-program (specifically, https://notabug.org/bignose/python-adventure/commit/7e0ade5342ae6f3fd1a0b1c677b7e5338c34d31e) is my suggested change to address this.

**Comment by brandon-rhodes** [comment]
Since this is a sample Python 3 project, I prefer to advertise its Python-ness very strongly by having folks invoke it explicitly through `python3 -m …`. Or, better yet, by playing from the Python prompt. I am not interested in competing with the official C version of Colossal Caves, which is what I hope folks will install when they want a normal system command that lets them play Adventure, so to avoid competition with the original let’s keep invoking this Adventure with Python.
